### ISSUE TITLE
docs\reference skipped as it doesn't contain .md

### ISSUE THREAD

**Issue by moonymachine** [mtirionMSFT/DocFxQuickStart#6]
When running the GenerateDocWebsite commandlet, the following warning is unavoidable: "WARNING: Folder C:\Users\[User]\Projects\DocFxQuickStart\QuickStart\docs\reference skipped as it doesn't contain *.md, *.swagger.json files. This might skip further sub-folders. Solve this by adding a README.md or INDEX.md in the folder." However, if you add a README.md file to that directory and run GenerateDocWebsite again, the file will be removed. Is there any way this warning could be avoided entirely?

**Comment by mtirionMSFT** [comment]
This is a warning in the DocFxTocGenerator part of the [docfx-companion-tools](https://github.com/Ellerbach/docfx-companion-tools). Please create an issue in that repo.
